### ISSUE TITLE
Update for changes in remark

### ISSUE THREAD

**Issue by wooorm** [sfrdmn/remark-yaml-annotations#15]
Hi! 👋

remark just changed: you can read more about the changed [here][1].

That means that this plugin doesn’t work with the latest remark. If you get around to updating, use the previously mentioned changelog for help, but feel free to respond below or ask questions on [Gitter][2]!

[1]: https://github.com/wooorm/remark/releases/tag/7.0.0
[2]: https://gitter.im/wooorm/remark
[3]: https://github.com/wooorm/remark/blob/master/doc/plugins.md#list-of-plugins

**Comment by sfrdmn** [comment]
Hi :) This was a bit of an experimental module really, don't have time ATM to update to the latest remark. I think what I can do is update the README to say "Ping me if you want to use this and I'll update it" because right now I don't need it

**Comment by wooorm** [comment]
Alright, yeah that seems good! 👌
